# Generated by Django 2.2.5 on 2020-04-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=120, unique=True)),
                ('position', models.CharField(blank=True, choices=[('Начальник цеха', 'Начальник цеха'), ('Начальник участка', 'Начальник участка'), ('Начальник ремонтной службы', 'Начальник ремонтной службы'), ('Работник', 'Работник')], max_length=30, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_manager.Area')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_manager.Workshop')),
            ],
        ),
    ]
