# Generated by Django 2.2.5 on 2020-04-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20200426_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_boss_repair',
            name='type_request',
            field=models.CharField(blank=True, choices=[('Профилактика', 'Профилактика'), ('Ремонт', 'Ремонт')], default='Профилактика', max_length=120, null=True),
        ),
    ]
