# Generated by Django 2.2.5 on 2020-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20200426_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_trouble',
            name='status',
            field=models.CharField(blank=True, default='Отправлено', max_length=120, null=True),
        ),
    ]
